"""Created by felipe-nunes on 22/09/2022

- Environment values
"""

class Environment:
    ARENA_HEIGHT_METERS = 4
    ARENA_MAX_X_METERS = 8
    ARENA_MAX_Y_METERS = 8

    COMM_DEFAULT_PORT = 14540
    COMM_DEFAULT_PROTOCOL = "udp"
    COMM_CONN_STRING = "{}://:{}".format(COMM_DEFAULT_PROTOCOL, COMM_DEFAULT_PORT)

    DRONE_MAX_SPEED_MS = 1
    DRONE_MIN_SPEED_MS = 0.2
    DRONE_TAKEOFF_SPEED_MS = 1
    DRONE_LAND_SPEED_MS = 1
    DRONE_TAKEOFF_HEIGHT_METERS = 5
    DRONE_LARC_TAKEOFF_HEIGHT_METERS = 1
    DRONE_SAFE_TAKEOFF_HEIGHT_METERS = 0.2
    DRONE_SEARCH_RADIUS_METERS = 1
    DRONE_SEARCH_IDLE_TIME_S = 2
    DRONE_SEARCH_SQUARE_EDGE_METERS = 2.0
    DRONE_SEARCH_NED_HEIGHT = -2.0

    SAFE_NET_LATERAL_DISTANCE_CENTIMETERS = 50
    SAFE_NET_ABOVE_DISTANCE_CENTIMETERS = 50
    SAFE_OFFBOARD_TIMEOUT_SECONDS = 10

