"""Created by felipe-nunes on 22/09/2022

- Environment values
"""


class Communication:
    DEFAULT_PORT = 14540
    DEFAULT_PROTOCOL = "udp"
    CONN_STRING = "{}://:{}".format(
        DEFAULT_PROTOCOL, DEFAULT_PORT)


class Arena:
    ARENA_HEIGHT_METERS = 4
    ARENA_MAX_X_METERS = 8
    ARENA_MAX_Y_METERS = 8

    SAFE_NET_LATERAL_DISTANCE_CENTIMETERS = 50
    SAFE_NET_ABOVE_DISTANCE_CENTIMETERS = 50


class Navigation:
    MAX_SPEED_MS = 1
    MIN_SPEED_MS = 0.2

    SEARCH_RADIUS_METERS = 1
    SEARCH_IDLE_TIME_S = 2
    SEARCH_SQUARE_EDGE_METERS = 2.0
    SEARCH_NED_HEIGHT = -2.0


class Takeoff:
    TIMEOUT_SECONDS = 10
    SPEED_MS = 1
    ALTITUDE_METERS = 10
    SAFE_ALTITUDE_METERS = 0.5
    LARC_ALTITUDE_METERS = 1


class Land:
    TIMEOUT_SECONDS = 5
    SPEED_MS = 1
